### ISSUE TITLE
Module name "Client" conflict

### ISSUE THREAD

**Issue by Pyo25** [klaviyo/klaviyo-ruby-sdk#1]
Hi @dano-klaviyo ,

I saw you deprecated the `ruby-klavio` gem and created this new gem a few days ago.

However I don't understand why you defined your main module as a super generic `Client` instead of using something more specific like `Klaviyo` or `KlaviyoClient`?!

We already have a `Client` module defined in our app!

Thanks,

**Comment by dano-klaviyo** [comment]
Hi @Pyo25, the intent was to keep all sdks consistent, but you bring a good point. The latest version of the sdk should follow the deprecated sdk module naming convention, specifically `Klaviyo`, to avoid module naming collisions.

Thanks for your feedback.
