### ISSUE TITLE
Getting Error 403 : The API key specified is invalid

### ISSUE THREAD

**Issue by gajendrajena** [klaviyo/klaviyo-ruby-sdk#11]
Hello,
I am trying to invoke 
```rb
Klaviyo::ListsSegments.add_members(list_id, opts)
```
Getting the following error, even the Private API Key is correct

```sh
Klaviyo::ApiError: Error message: the server returns an error
HTTP status code: 403
Response headers: {"date"=>"Mon, 31 Oct 2022 06:44:39 GMT", "content-type"=>"application/json", "content-length"=>"47", "cf-ray"=>"762a6c626a373c01-BLR", "allow"=>"GET, POST, DELETE, HEAD, OPTIONS", "vary"=>"Cookie", "cf-cache-status"=>"DYNAMIC", "x-robots-tag"=>"noindex, nofollow", "server"=>"cloudflare"}
Response body: {"message":"The API key specified is invalid."}
from /Users/gajendrajena/.rvm/gems/ruby-2.6.6/gems/klaviyo_sdk-1.0.5.20220329/lib/klaviyo_sdk/api_client.rb:65:in `call_api'
```
Can someone help here?

**Comment by dano-klaviyo** [comment]
Hi, do you get the same error when you try to make a request directly using the api (i.e. using `curl`): https://developers.klaviyo.com/en/v1-2/reference/add-members

**Comment by gajendrajena** [comment]
Hi @dano-klaviyo ,
I am getting success response via curl.
And the emails are getting added to the list when I am doing it via curl.

**Comment by gajendrajena** [comment]
@dano-klaviyo thanks, though we are using the same configuration, our app was reseting the api key.
Finally got it working, thanks for pointing out.
